FROM python:3.10-slim

WORKDIR /app

# Install system dependencies if any (e.g. gcc for some python libs)
# RUN apt-get update && apt-get install -y gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source
COPY . .

# Compile Protos at build time
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. protos/service.proto

# Set Python path so 'protos' and 'services' are Importable
ENV PYTHONPATH=/app

# Default command (overriden by docker-compose/stack per service)
CMD ["python", "services/gateway/main.py"]
