FROM python:3.10-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY main.py .
COPY tags/ ./tags/

# Variable de entorno para el backend
ENV API_URL=http://backend:8000

# El contenedor se mantiene corriendo
CMD ["python", "main.py"]
