# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import service_pb2 as protos_dot_service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataNodeServiceStub(object):
    """==================== DATA NODE SERVICE ====================
    Runs on every storage node. Handles raw data IO.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/tagfs.DataNodeService/Ping',
                request_serializer=protos_dot_service__pb2.PingRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.PingResponse.FromString,
                _registered_method=True)
        self.StoreChunk = channel.stream_unary(
                '/tagfs.DataNodeService/StoreChunk',
                request_serializer=protos_dot_service__pb2.FileChunk.SerializeToString,
                response_deserializer=protos_dot_service__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.RetrieveChunk = channel.unary_stream(
                '/tagfs.DataNodeService/RetrieveChunk',
                request_serializer=protos_dot_service__pb2.FileRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.FileChunk.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/tagfs.DataNodeService/DeleteFile',
                request_serializer=protos_dot_service__pb2.FileRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ReplicateFrom = channel.unary_unary(
                '/tagfs.DataNodeService/ReplicateFrom',
                request_serializer=protos_dot_service__pb2.ReplicationRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.ReplicationResponse.FromString,
                _registered_method=True)


class DataNodeServiceServicer(object):
    """==================== DATA NODE SERVICE ====================
    Runs on every storage node. Handles raw data IO.

    """

    def Ping(self, request, context):
        """Check health (gRPC standard health check could also be used)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreChunk(self, request_iterator, context):
        """Write a file stream to disk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChunk(self, request, context):
        """Read a file from disk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Delete a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateFrom(self, request, context):
        """Replicate file from source to target DataNode (for re-replication)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=protos_dot_service__pb2.PingRequest.FromString,
                    response_serializer=protos_dot_service__pb2.PingResponse.SerializeToString,
            ),
            'StoreChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.StoreChunk,
                    request_deserializer=protos_dot_service__pb2.FileChunk.FromString,
                    response_serializer=protos_dot_service__pb2.StoreResponse.SerializeToString,
            ),
            'RetrieveChunk': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveChunk,
                    request_deserializer=protos_dot_service__pb2.FileRequest.FromString,
                    response_serializer=protos_dot_service__pb2.FileChunk.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=protos_dot_service__pb2.FileRequest.FromString,
                    response_serializer=protos_dot_service__pb2.DeleteResponse.SerializeToString,
            ),
            'ReplicateFrom': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateFrom,
                    request_deserializer=protos_dot_service__pb2.ReplicationRequest.FromString,
                    response_serializer=protos_dot_service__pb2.ReplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tagfs.DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tagfs.DataNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """==================== DATA NODE SERVICE ====================
    Runs on every storage node. Handles raw data IO.

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.DataNodeService/Ping',
            protos_dot_service__pb2.PingRequest.SerializeToString,
            protos_dot_service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/tagfs.DataNodeService/StoreChunk',
            protos_dot_service__pb2.FileChunk.SerializeToString,
            protos_dot_service__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tagfs.DataNodeService/RetrieveChunk',
            protos_dot_service__pb2.FileRequest.SerializeToString,
            protos_dot_service__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.DataNodeService/DeleteFile',
            protos_dot_service__pb2.FileRequest.SerializeToString,
            protos_dot_service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateFrom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.DataNodeService/ReplicateFrom',
            protos_dot_service__pb2.ReplicationRequest.SerializeToString,
            protos_dot_service__pb2.ReplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MetadataServiceStub(object):
    """==================== METADATA SERVICE ====================
    Runs on the Manager node(s). Handles logic and coordination.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignWrite = channel.unary_unary(
                '/tagfs.MetadataService/AssignWrite',
                request_serializer=protos_dot_service__pb2.WriteRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.WriteAllocation.FromString,
                _registered_method=True)
        self.CommitWrite = channel.unary_unary(
                '/tagfs.MetadataService/CommitWrite',
                request_serializer=protos_dot_service__pb2.CommitRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.LocateFile = channel.unary_unary(
                '/tagfs.MetadataService/LocateFile',
                request_serializer=protos_dot_service__pb2.FileRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.FileLocation.FromString,
                _registered_method=True)
        self.AddTags = channel.unary_unary(
                '/tagfs.MetadataService/AddTags',
                request_serializer=protos_dot_service__pb2.TagRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.TagResponse.FromString,
                _registered_method=True)
        self.RemoveTags = channel.unary_unary(
                '/tagfs.MetadataService/RemoveTags',
                request_serializer=protos_dot_service__pb2.TagRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.TagResponse.FromString,
                _registered_method=True)
        self.UpdateTags = channel.unary_unary(
                '/tagfs.MetadataService/UpdateTags',
                request_serializer=protos_dot_service__pb2.UpdateTagsRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.TagResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/tagfs.MetadataService/ListFiles',
                request_serializer=protos_dot_service__pb2.ListRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.ListResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/tagfs.MetadataService/DeleteFile',
                request_serializer=protos_dot_service__pb2.FileRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Election = channel.unary_unary(
                '/tagfs.MetadataService/Election',
                request_serializer=protos_dot_service__pb2.ElectionRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.Coordinator = channel.unary_unary(
                '/tagfs.MetadataService/Coordinator',
                request_serializer=protos_dot_service__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.CoordinatorResponse.FromString,
                _registered_method=True)
        self.LeaderHeartbeat = channel.unary_unary(
                '/tagfs.MetadataService/LeaderHeartbeat',
                request_serializer=protos_dot_service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GossipPush = channel.unary_unary(
                '/tagfs.MetadataService/GossipPush',
                request_serializer=protos_dot_service__pb2.GossipUpdate.SerializeToString,
                response_deserializer=protos_dot_service__pb2.GossipAck.FromString,
                _registered_method=True)
        self.GossipPull = channel.unary_unary(
                '/tagfs.MetadataService/GossipPull',
                request_serializer=protos_dot_service__pb2.GossipRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.GossipUpdate.FromString,
                _registered_method=True)
        self.PropagatePending = channel.unary_unary(
                '/tagfs.MetadataService/PropagatePending',
                request_serializer=protos_dot_service__pb2.PendingUploadEntry.SerializeToString,
                response_deserializer=protos_dot_service__pb2.GossipAck.FromString,
                _registered_method=True)
        self.CompareMerkleRoot = channel.unary_unary(
                '/tagfs.MetadataService/CompareMerkleRoot',
                request_serializer=protos_dot_service__pb2.MerkleRootRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.MerkleRootResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/tagfs.MetadataService/Ping',
                request_serializer=protos_dot_service__pb2.PingRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.PingResponse.FromString,
                _registered_method=True)


class MetadataServiceServicer(object):
    """==================== METADATA SERVICE ====================
    Runs on the Manager node(s). Handles logic and coordination.

    """

    def AssignWrite(self, request, context):
        """Gateway requests write allocation (Where should I put this file?)
        Returns N=3 DataNodes to write to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitWrite(self, request, context):
        """Gateway confirms write success (Commit)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocateFile(self, request, context):
        """Gateway requests file location (Where is this file?)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTags(self, request, context):
        """Metadata operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Bully Algorithm RPCs for Leader Election
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaderHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GossipPush(self, request, context):
        """Gossip Protocol RPCs for Metadata Propagation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GossipPull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagatePending(self, request, context):
        """Replication of Pending Uploads (Pre-Commit)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareMerkleRoot(self, request, context):
        """Merkle Tree Anti-Entropy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health Check for Peer Discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignWrite,
                    request_deserializer=protos_dot_service__pb2.WriteRequest.FromString,
                    response_serializer=protos_dot_service__pb2.WriteAllocation.SerializeToString,
            ),
            'CommitWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitWrite,
                    request_deserializer=protos_dot_service__pb2.CommitRequest.FromString,
                    response_serializer=protos_dot_service__pb2.CommitResponse.SerializeToString,
            ),
            'LocateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LocateFile,
                    request_deserializer=protos_dot_service__pb2.FileRequest.FromString,
                    response_serializer=protos_dot_service__pb2.FileLocation.SerializeToString,
            ),
            'AddTags': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTags,
                    request_deserializer=protos_dot_service__pb2.TagRequest.FromString,
                    response_serializer=protos_dot_service__pb2.TagResponse.SerializeToString,
            ),
            'RemoveTags': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTags,
                    request_deserializer=protos_dot_service__pb2.TagRequest.FromString,
                    response_serializer=protos_dot_service__pb2.TagResponse.SerializeToString,
            ),
            'UpdateTags': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTags,
                    request_deserializer=protos_dot_service__pb2.UpdateTagsRequest.FromString,
                    response_serializer=protos_dot_service__pb2.TagResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=protos_dot_service__pb2.ListRequest.FromString,
                    response_serializer=protos_dot_service__pb2.ListResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=protos_dot_service__pb2.FileRequest.FromString,
                    response_serializer=protos_dot_service__pb2.DeleteResponse.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=protos_dot_service__pb2.ElectionRequest.FromString,
                    response_serializer=protos_dot_service__pb2.ElectionResponse.SerializeToString,
            ),
            'Coordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinator,
                    request_deserializer=protos_dot_service__pb2.CoordinatorRequest.FromString,
                    response_serializer=protos_dot_service__pb2.CoordinatorResponse.SerializeToString,
            ),
            'LeaderHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaderHeartbeat,
                    request_deserializer=protos_dot_service__pb2.HeartbeatRequest.FromString,
                    response_serializer=protos_dot_service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GossipPush': grpc.unary_unary_rpc_method_handler(
                    servicer.GossipPush,
                    request_deserializer=protos_dot_service__pb2.GossipUpdate.FromString,
                    response_serializer=protos_dot_service__pb2.GossipAck.SerializeToString,
            ),
            'GossipPull': grpc.unary_unary_rpc_method_handler(
                    servicer.GossipPull,
                    request_deserializer=protos_dot_service__pb2.GossipRequest.FromString,
                    response_serializer=protos_dot_service__pb2.GossipUpdate.SerializeToString,
            ),
            'PropagatePending': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagatePending,
                    request_deserializer=protos_dot_service__pb2.PendingUploadEntry.FromString,
                    response_serializer=protos_dot_service__pb2.GossipAck.SerializeToString,
            ),
            'CompareMerkleRoot': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareMerkleRoot,
                    request_deserializer=protos_dot_service__pb2.MerkleRootRequest.FromString,
                    response_serializer=protos_dot_service__pb2.MerkleRootResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=protos_dot_service__pb2.PingRequest.FromString,
                    response_serializer=protos_dot_service__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tagfs.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tagfs.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """==================== METADATA SERVICE ====================
    Runs on the Manager node(s). Handles logic and coordination.

    """

    @staticmethod
    def AssignWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/AssignWrite',
            protos_dot_service__pb2.WriteRequest.SerializeToString,
            protos_dot_service__pb2.WriteAllocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/CommitWrite',
            protos_dot_service__pb2.CommitRequest.SerializeToString,
            protos_dot_service__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/LocateFile',
            protos_dot_service__pb2.FileRequest.SerializeToString,
            protos_dot_service__pb2.FileLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/AddTags',
            protos_dot_service__pb2.TagRequest.SerializeToString,
            protos_dot_service__pb2.TagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/RemoveTags',
            protos_dot_service__pb2.TagRequest.SerializeToString,
            protos_dot_service__pb2.TagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/UpdateTags',
            protos_dot_service__pb2.UpdateTagsRequest.SerializeToString,
            protos_dot_service__pb2.TagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/ListFiles',
            protos_dot_service__pb2.ListRequest.SerializeToString,
            protos_dot_service__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/DeleteFile',
            protos_dot_service__pb2.FileRequest.SerializeToString,
            protos_dot_service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/Election',
            protos_dot_service__pb2.ElectionRequest.SerializeToString,
            protos_dot_service__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Coordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/Coordinator',
            protos_dot_service__pb2.CoordinatorRequest.SerializeToString,
            protos_dot_service__pb2.CoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaderHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/LeaderHeartbeat',
            protos_dot_service__pb2.HeartbeatRequest.SerializeToString,
            protos_dot_service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GossipPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/GossipPush',
            protos_dot_service__pb2.GossipUpdate.SerializeToString,
            protos_dot_service__pb2.GossipAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GossipPull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/GossipPull',
            protos_dot_service__pb2.GossipRequest.SerializeToString,
            protos_dot_service__pb2.GossipUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagatePending(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/PropagatePending',
            protos_dot_service__pb2.PendingUploadEntry.SerializeToString,
            protos_dot_service__pb2.GossipAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareMerkleRoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/CompareMerkleRoot',
            protos_dot_service__pb2.MerkleRootRequest.SerializeToString,
            protos_dot_service__pb2.MerkleRootResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tagfs.MetadataService/Ping',
            protos_dot_service__pb2.PingRequest.SerializeToString,
            protos_dot_service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
